version: "3"

volumes:
  irods_database:
    driver: local
  irods_config:
    driver: local
  irods_ssl:
    driver: local
  irods_packages:
    driver: local

services:
  database:
    image: postgres:9.1
    volumes:
      - irods_database:/var/lib/postgresql/data
      - ./etc/pgs_init.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh:ro
    env_file:
      - ./env/db.env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - internal

  icat:
    build:
      context: build
      dockerfile: Dockerfile.icat
    hostname: icat.local
    volumes:
      - irods_config:/var/lib/irods
      - irods_ssl:/var/lib/ssl
      - irods_packages:/packages
    depends_on:
      - database
    links:
      - database
    env_file:
      - ./env/db.env
      - ./env/irods.env
      - ./env/sram.env
    environment:
      IRODS_DB_HOST: database
      DATABASE_TYPE: "postgres"
      SESSION_MINUTES: 60
    networks:
      - internal

  icommands:
    build:
      context: build
      dockerfile: Dockerfile.icommands
    hostname: irods-demo
    volumes:
      - irods_ssl:/var/lib/ssl
      - irods_packages:/packages-icat:ro
    links:
      - icat
    env_file:
      - ./env/irods.env
      - ./env/ldap.env
    ports:
      - "2222:22"
    environment:
      LOG_LEVEL: INFO
      IRODS_JSON: /etc/default/default_irods_environment.json
      IRODS_CERT: /var/lib/ssl/irods.crt
      IRODS_HOST: icat
      IRODS_PORT: 1247
      SSH_HOST: localhost
      SSH_PORT: 22
    networks:
      - internal

networks:
  internal:
